# Generated by Django 4.2.29 on 2026-03-24 14:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('industry', models.CharField(choices=[('retail', 'Retail'), ('technology', 'Technology'), ('food_beverage', 'Food & Beverage'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('finance', 'Finance'), ('construction', 'Construction'), ('agriculture', 'Agriculture'), ('logistics', 'Logistics'), ('entertainment', 'Entertainment'), ('real_estate', 'Real Estate'), ('consulting', 'Consulting'), ('freelance', 'Freelance'), ('other', 'Other')], default='other', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'businesses',
                'db_table': 'businesses',
                'ordering': ['-created_at'],
            },
        ),
    ]
