from rest_framework import serializers
from .models import Payment


class PaymentSerializer(serializers.ModelSerializer):
    class Meta:
        model = Payment
        fields = ['id', 'business_id', 'amount', 'currency', 'status', 'description',
                  'reference', 'interswitch_ref', 'created_at']
        read_only_fields = ['id', 'status', 'reference', 'interswitch_ref', 'created_at']


class InitiatePaymentSerializer(serializers.Serializer):
    business_id = serializers.UUIDField()
    amount = serializers.DecimalField(max_digits=12, decimal_places=2)
    description = serializers.CharField(max_length=255)
    callback_url = serializers.URLField(required=False, default="http://localhost:3000/payment-callback")
    # auth_data: Encrypted card data generated by the ISW JS SDK on the frontend.
    # The frontend captures card number, expiry, CVV, PIN → encrypts using ISW public key
    # → sends the resulting base64 string here.
    auth_data = serializers.CharField(
        help_text="Encrypted card details from Interswitch JS SDK (base64 string)"
    )
    customer_id = serializers.CharField(
        help_text="User or business ID of the payer"
    )


class AuthenticateOTPSerializer(serializers.Serializer):
    """
    Used after initiate_payment() returns responseCode 'T0'.
    The frontend collects the OTP from the cardholder and submits it here.
    """
    reference = serializers.CharField(
        help_text="Your internal transaction reference (LDG-XXXXX)"
    )
    payment_id = serializers.CharField(
        help_text="paymentId from the initiate payment response"
    )
    transaction_id = serializers.CharField(
        help_text="transactionId from the initiate payment response"
    )
    otp = serializers.CharField(
        min_length=4, max_length=10,
        help_text="One-time password sent to the cardholder's phone"
    )
    eci_flag = serializers.CharField(
        required=False, allow_null=True, max_length=10,
        help_text="Electronic Commerce Indicator (optional, typically '07' for Visa)"
    )


class VerifyPaymentSerializer(serializers.Serializer):
    """
    Verify final status of a payment from Interswitch.
    Call this after OTP auth completes or after an immediate '00' from initiate.
    """
    reference = serializers.CharField(
        help_text="Your internal transaction reference (LDG-XXXXX)"
    )
    amount = serializers.DecimalField(
        max_digits=12, decimal_places=2,
        help_text="Original payment amount in Naira"
    )

