"""Interswitch Payment Services."""
import base64
import requests
import time
from django.conf import settings

class InterswitchService:
    @staticmethod
    def get_access_token():
        """
        Retrieves OAuth 2.0 access token from Interswitch passport.
        """
        auth_string = f"{settings.ISW_CLIENT_ID}:{settings.ISW_SECRET_KEY}"
        b64_auth = base64.b64encode(auth_string.encode('utf-8')).decode('utf-8')
        
        headers = {
            "Authorization": f"Basic {b64_auth}",
            "Content-Type": "application/x-www-form-urlencoded"
        }
        
        data = {
            "grant_type": "client_credentials"
        }
        
        url = f"{settings.ISW_BASE_URL}/passport/oauth/token"
        
        try:
            # We bypass real HTTP calls in tests normally.
            # But here is the real implementation for production.
            response = requests.post(url, headers=headers, data=data, timeout=10)
            if response.status_code == 200:
                return response.json().get('access_token')
            else:
                print(f"Interswitch Token Error: {response.text}")
        except Exception as e:
            print(f"Token Network Error: {e}")
            
        return None

    @staticmethod
    def initiate_payment(amount, reference, callback_url, auth_data, customer_id):
        """
        Initiates a card payment via the Interswitch Card Payments API.
        
        :param amount: Payment amount in Naira (will be converted to kobo)
        :param reference: Unique transaction reference (e.g. LDG-ABC123)
        :param callback_url: URL Interswitch redirects to after payment
        :param auth_data: Encrypted card data string (generated by frontend using ISW JS SDK)
        :param customer_id: The user/business ID making the payment
        :returns: Raw ISW response dict, or None on failure
        
        Expected ISW response codes:
          "00" -> Approved immediately (no OTP needed)
          "T0" -> OTP sent — must call authenticate_otp() next
          "S0" -> Visa 3DS redirect required
        """
        token = InterswitchService.get_access_token()
        if not token:
            return None
            
        url = f"{settings.ISW_BASE_URL}/api/v3/purchases"
        headers = {
            "Authorization": f"Bearer {token}",
            "Content-Type": "application/json"
        }
        
        payload = {
            "customerId": str(customer_id),
            "amount": str(int(amount * 100)),  # Amount in kobo
            "currency": "NGN",
            "authData": auth_data,             # Encrypted card details from frontend
            "transactionRef": reference,
            "siteRedirectURL": callback_url,
        }
        
        try:
            response = requests.post(url, headers=headers, json=payload, timeout=10)
            if response.status_code in [200, 201]:
                return response.json()
            else:
                print(f"ISW Purchase Error {response.status_code}: {response.text}")
        except Exception as e:
            print(f"ISW Initiate Payment Error: {e}")
            
        return None

    @staticmethod
    def authenticate_otp(payment_id, otp, transaction_id, eci_flag=None):
        """
        Step 2 of card payment: Submit OTP entered by the customer.
        Called only when initiate_payment() returns responseCode "T0"
        (Verve / Mastercard cards).

        :param payment_id: paymentId from the initiate_payment() response
        :param otp: One-time password entered by the cardholder
        :param transaction_id: transactionId from the initiate_payment() response
        :returns: ISW response dict with responseCode "00" on success
        """
        token = InterswitchService.get_access_token()
        if not token:
            return None

        url = f"{settings.ISW_BASE_URL}/api/v3/purchases/otps/auths"
        headers = {
            "Authorization": f"Bearer {token}",
            "Content-Type": "application/json"
        }

        payload = {
            "paymentId": str(payment_id),
            "otp": str(otp),
            "transactionId": str(transaction_id),
        }
        
        if eci_flag:
            payload["eciFlag"] = str(eci_flag)

        try:
            response = requests.post(url, headers=headers, json=payload, timeout=10)
            if response.status_code in [200, 201]:
                return response.json()
            else:
                print(f"ISW OTP Auth Error {response.status_code}: {response.text}")
        except Exception as e:
            print(f"ISW OTP Auth Network Error: {e}")

        return None

    @staticmethod
    def verify_transaction(transaction_reference, amount):
        """
        Step 3: Confirm final transaction status from Interswitch.
        Call this after OTP auth succeeds OR after an immediate "00" response
        from initiate_payment() to get the full confirmed record.

        :param transaction_reference: The unique ref string you generated (e.g. LDG-ABC123)
        :param amount: Transaction amount in Naira (converted to kobo internally)
        :returns: ISW response dict with ResponseCode "00" on confirmed success
        """
        token = InterswitchService.get_access_token()
        if not token:
            return None

        url = f"{settings.ISW_BASE_URL}/collections/api/v1/gettransaction"
        headers = {
            "Authorization": f"Bearer {token}",
        }

        params = {
            "merchantcode": settings.ISW_MERCHANT_CODE,
            "transactionreference": transaction_reference,
            "amount": str(int(amount * 100)),  # In kobo
        }

        try:
            response = requests.get(url, headers=headers, params=params, timeout=10)
            if response.status_code == 200:
                return response.json()
            else:
                print(f"ISW Verify Error {response.status_code}: {response.text}")
        except Exception as e:
            print(f"ISW Verify Network Error: {e}")

        return None
